name: Deploy Toolkit 2

on:
  push:
    branches:
      - main
      - staging-internal
  pull_request:
    branches:
      - main
      - staging-internal
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R and Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libudunits2-dev libgdal-dev
          sudo apt-get install libmagick++-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c("bookdown", "rmarkdown", "plotly", "shiny", "tidycensus", "tidyverse", "viridis", "ggmap", "ggplot2", "maps", "dplyr", "knitr", "latticeExtra", "pals", "classInt", "sf", "udunits2", "tmap", "lubridate", "gifski", "magick", "cowplot"))'
          R -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager"); BiocManager::install("Biobase")'

      - name: Build site for main branch
        run: R -e 'bookdown::render_book()'

      - name: Deploy to GitHub pages ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs

  deploy_staging:
    if: github.ref == 'refs/heads/staging-internal'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R and Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libudunits2-dev libgdal-dev
          sudo apt-get install libmagick++-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c("bookdown", "rmarkdown", "plotly", "shiny", "tidycensus", "tidyverse", "viridis", "ggmap", "ggplot2", "maps", "dplyr", "knitr", "latticeExtra", "pals", "classInt", "sf", "udunits2", "tmap", "lubridate", "gifski", "magick", "cowplot"))'
          R -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager"); BiocManager::install("Biobase")'

      - name: Build site for staging branch
        run: R -e 'bookdown::render_book()'

      - name: Deploy to GitHub pages ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: staging-pages
          folder: docs